### REQUIRED SETTINGS ###

# Set a plain language title for the site.
title: Site Nav Test Drive

# Write a short description for the site. This is used for "meta description."
description: Try out new navigation with usability tests in realtime on a working site

# Enable for live hosting on GitHub Pages.
# It should start with a slash (/) and then match the name of your repository exactly.
baseurl: /site-nav-test-drive

# =============================================================================

### TEST SITE SETTINGS ###

# The URL of the site you want to test.
test-site: "http://www.usa.gov/"

# The amount of offsite needed to cover the test site nav with the new nav.
# Increase the negative number value to move the test site "up" so more of it is covered by the new nav.
nav-offset: -24

# =============================================================================

### OPTIONAL SETTINGS ###

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Remove generation of additional style.css
theme: null